### ISSUE TITLE
Release versioning

### ISSUE THREAD

**Issue by Justinzobel** [linuxdeepin/deepin-sound-theme#1]
I'm trying to keep Deepin packaged for Solus but your versioning is all over the place. Is it possible to follow a standardised version across all of the repositories? Some are versioned with dates, others with 15.x, others with 5.x, etc.

**Comment by BLumia** [comment]
Most package should use 5.x now if I remember correctly.. Some package are already using a version number which the first version number is greater than 5 (like the one using date). I think maybe they are avoiding change the version number of these package which may probably cause upgrade issue to end user. That's all what I know, hope that helps.

**Comment by Justinzobel** [comment]
Thanks for the update. Do you have a document that describes how your version is and will be in the future?

**Comment by BLumia** [comment]
Sorry I don't have it, maybe @xmuli or @felixonmars can give you more details I guess.

**Comment by felixonmars** [comment]
@BLumia we used to have deepin-code-release but it didn't work well either. In the past few years I often suggest other distributions to follow Arch versions on a stable release period.
